# Generated by Django 6.0 on 2026-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
