# Generated by Django 6.0 on 2026-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='duration_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
